import LegalPage, { type LegalSection } from "@/components/legal/LegalPage";

export const metadata = {
  title: "Terms of Use",
  description:
    "Terms of Use for Nyaya Vidhi — the legally binding agreement between you and Nyaya Vidhi governing your access to and use of the Platform under Indian law.",
  alternates: { canonical: "/terms" },
  robots: { index: true, follow: true },
};

const sections: LegalSection[] = [
  {
    id: "acceptance",
    number: "1",
    title: "Acceptance of Terms",
    body: (
      <>
        <p>
          These Terms of Use (the <strong>“Terms”</strong>) constitute a
          legally binding electronic contract between you (the{" "}
          <strong>“User”</strong> or <strong>“you”</strong>) and Nyaya Vidhi
          (the <strong>“Platform”</strong>, <strong>“we”</strong>,{" "}
          <strong>“us”</strong>, or <strong>“our”</strong>), governing your
          access to and use of <a href="https://nyayavidhi.in">nyayavidhi.in</a>{" "}
          and any related sub-domains, content, applications, newsletters, and
          services (collectively, the <strong>“Services”</strong>).
        </p>
        <p>
          These Terms are an electronic record within the meaning of the{" "}
          <strong>Information Technology Act, 2000</strong>, and the rules
          made thereunder, and the provisions pertaining to electronic records
          in various statutes as amended by the IT Act. They are generated by
          a computer system and do not require any physical or digital
          signature. Your continued use of the Services constitutes your{" "}
          <strong>unconditional acceptance</strong> of these Terms, our{" "}
          <a href="/privacy">Privacy Policy</a>, and our{" "}
          <a href="/disclaimer">Disclaimer</a>, each of which is incorporated
          by reference. If you do not agree, please discontinue use of the
          Services immediately.
        </p>
      </>
    ),
  },
  {
    id: "eligibility",
    number: "2",
    title: "Eligibility & Capacity",
    body: (
      <>
        <p>
          By using the Services, you represent and warrant that you are
          competent to contract within the meaning of <strong>Section 11
          of the Indian Contract Act, 1872</strong>, that is, you:
        </p>
        <ol>
          <li>
            have attained the age of <strong>eighteen (18) years</strong>;
          </li>
          <li>are of sound mind; and</li>
          <li>
            are not disqualified from contracting by any law to which you are
            subject.
          </li>
        </ol>
        <p>
          If you are accessing the Services on behalf of an entity, you
          represent that you have the authority to bind such entity to these
          Terms, in which case <strong>“you”</strong> shall refer to that
          entity. Persons who are minors or who are otherwise legally
          incompetent to enter into contracts are not permitted to use the
          Services without the involvement of a lawful guardian.
        </p>
      </>
    ),
  },
  {
    id: "nature",
    number: "3",
    title: "Nature of the Services",
    body: (
      <>
        <p>
          Nyaya Vidhi is an <strong>educational publication</strong> on Indian
          law. The Services include, among other things, statute explainers,
          plain-language summaries, “Know Your Rights” cards, learning paths,
          curated case studies, and a periodic newsletter. The Services are
          intended to improve general public understanding of the law.
        </p>
        <p>
          The Platform is <strong>not a law firm</strong>; it does not provide
          legal services, does not offer legal representation, does not draft
          legal instruments for clients, and does not solicit legal work
          within the meaning of the Bar Council of India Rules. For any
          fact-specific legal matter, you must consult a duly enrolled
          advocate. Please refer to our <a href="/disclaimer">Disclaimer</a>{" "}
          for further detail.
        </p>
      </>
    ),
  },
  {
    id: "license",
    number: "4",
    title: "Licence to Use",
    body: (
      <>
        <p>
          Subject to your continued compliance with these Terms, we grant you
          a limited, personal, non-exclusive, non-transferable, non-sub-licensable,
          revocable licence to access and use the Services for your{" "}
          <strong>personal, non-commercial, educational</strong> purposes.
        </p>
        <p>
          All rights not expressly granted to you in these Terms are reserved
          by us. No licence is granted to you by implication, estoppel, or
          otherwise. You shall not acquire any ownership interest in the
          Services or in any content made available through the Services by
          virtue of these Terms.
        </p>
      </>
    ),
  },
  {
    id: "ip",
    number: "5",
    title: "Intellectual Property",
    body: (
      <>
        <p>
          All right, title, and interest in and to the Services — including
          all original commentary, design, source code, illustrations,
          curation, learning paths, branding, logos, the “Nyaya Vidhi” name,
          and the underlying database — are owned by us or our licensors and
          are protected under the <strong>Copyright Act, 1957</strong>, the{" "}
          <strong>Trade Marks Act, 1999</strong>, the{" "}
          <strong>Designs Act, 2000</strong>, applicable international
          conventions, and other intellectual-property laws.
        </p>
        <p>
          The bare text of statutes, rules, regulations, notifications, and
          judgments of Indian courts is in the public domain by virtue of{" "}
          <strong>Section 52(1)(q) of the Copyright Act, 1957</strong>. Our
          original commentary, structure, classification, and presentation of
          such public-domain material is, however, a copyrightable compilation
          and an original literary work and is protected accordingly.
        </p>
        <p>
          You may make a single copy of any page for your personal,
          non-commercial reference. Any other reproduction, redistribution,
          republication, scraping, framing, or commercial exploitation of any
          portion of the Services — in any medium, in whole or in part —
          without our prior written permission is strictly prohibited and may
          attract civil and criminal action under applicable law.
        </p>
      </>
    ),
  },
  {
    id: "user-conduct",
    number: "6",
    title: "Acceptable Use & Prohibited Conduct",
    body: (
      <>
        <p>
          You agree to use the Services in good faith and in compliance with
          all applicable laws, including the IT Act, the Bharatiya Nyaya
          Sanhita, 2023, the Bharatiya Nagarik Suraksha Sanhita, 2023, and
          Rule 3(1)(b) of the{" "}
          <em>
            Information Technology (Intermediary Guidelines and Digital Media
            Ethics Code) Rules, 2021
          </em>
          .
        </p>
        <p>You shall not, and shall not permit any third party to:</p>
        <ol>
          <li>
            host, display, upload, modify, publish, transmit, store, update,
            or share any information that is unlawful, defamatory, obscene,
            paedophilic, invasive of another’s privacy, insulting or harassing
            on the basis of gender, libellous, racially or ethnically
            objectionable, relating or encouraging money laundering or
            gambling, or otherwise inconsistent with or contrary to the laws
            in force;
          </li>
          <li>
            impersonate any person, misrepresent your affiliation with any
            person or entity, or falsely state or otherwise misrepresent
            yourself;
          </li>
          <li>
            use the Services to threaten the unity, integrity, defence,
            security, or sovereignty of India, friendly relations with foreign
            States, or public order, or cause incitement to the commission of
            any cognisable offence;
          </li>
          <li>
            access or attempt to access the Services by any means other than
            the interface provided, including through automated means, bots,
            scrapers, or crawlers, except for crawlers that respect our{" "}
            <code>robots.txt</code>;
          </li>
          <li>
            introduce viruses, worms, malware, ransomware, time-bombs, Trojan
            horses, or any other malicious code; attempt to gain unauthorised
            access to any portion of the Services, related systems, networks,
            or any data; or interfere with or disrupt the integrity or
            performance of the Services;
          </li>
          <li>
            reverse-engineer, decompile, disassemble, or otherwise attempt to
            derive the source code, underlying ideas, or algorithms of any
            part of the Services;
          </li>
          <li>
            infringe any patent, trademark, copyright, or other proprietary
            right of any party;
          </li>
          <li>
            scrape or systematically collect data from the Services to build a
            competing product, train a machine-learning model, or for any
            commercial purpose, without our prior written consent;
          </li>
          <li>
            transmit any content that contains software viruses or any other
            computer code, files, or programmes designed to interrupt,
            destroy, or limit the functionality of any computer resource; or
          </li>
          <li>
            violate any applicable law, regulation, or judicial or
            quasi-judicial order.
          </li>
        </ol>
        <p>
          Violation of this Section may result in immediate termination of
          your access to the Services, removal of offending content, and
          referral to law-enforcement authorities, in addition to any other
          legal remedies available to us.
        </p>
      </>
    ),
  },
  {
    id: "user-content",
    number: "7",
    title: "User Submissions & Feedback",
    body: (
      <>
        <p>
          If you submit any feedback, suggestions, corrections, ideas, or
          other communication to us (collectively, <strong>“Submissions”</strong>),
          you grant us a worldwide, royalty-free, perpetual, irrevocable,
          sub-licensable, and transferable licence to use, reproduce, modify,
          adapt, publish, translate, distribute, and display such Submissions
          in any media. You represent and warrant that you own or otherwise
          control all rights to your Submissions and that the Submissions do
          not violate the rights of any third party.
        </p>
        <p>
          We are not obliged to act on any Submission, to attribute any
          Submission to you, or to keep any Submission confidential.
        </p>
      </>
    ),
  },
  {
    id: "intermediary",
    number: "8",
    title: "Intermediary Status & Safe Harbour",
    body: (
      <>
        <p>
          To the extent the Platform hosts third-party content or
          User-submitted content, it functions as an{" "}
          <strong>“intermediary”</strong> as defined under Section 2(1)(w) of
          the IT Act and is entitled to the safe-harbour protection under
          Section 79 of the IT Act, read with the Intermediary Rules, 2021.
        </p>
        <p>
          We exercise <strong>due diligence</strong> in publishing the rules
          and regulations, privacy policy, and user agreement; in informing
          users of the categories of content prohibited under Rule 3(1)(b);
          and in establishing a grievance-redress mechanism. We are not, and
          shall not be deemed to be, the originator, sponsor, or endorser of
          any third-party content unless expressly indicated.
        </p>
      </>
    ),
  },
  {
    id: "newsletter",
    number: "9",
    title: "Newsletter & Communications",
    body: (
      <>
        <p>
          When you subscribe to our newsletter, you consent to receive
          electronic communications from us at the email address you provide.
          We comply with applicable rules under the IT Act and TRAI
          regulations on commercial communications.
        </p>
        <p>
          Every commercial email we send includes an{" "}
          <strong>unsubscribe link</strong>. You may withdraw your consent at
          any time by clicking that link or by writing to{" "}
          <a href="mailto:grievance@nyayavidhi.in">grievance@nyayavidhi.in</a>.
        </p>
      </>
    ),
  },
  {
    id: "third-party",
    number: "10",
    title: "Third-Party Links & Resources",
    body: (
      <p>
        The Services may contain links to third-party websites, statutes
        hosted on Government portals, judgments hosted by various courts, and
        external resources. Such links are provided solely for the convenience
        of Users and do not constitute our endorsement of, or our
        responsibility for, the third-party content. Your use of any
        third-party resource is at your own risk and is subject to the terms
        and policies of that third party.
      </p>
    ),
  },
  {
    id: "warranties",
    number: "11",
    title: "Disclaimer of Warranties",
    body: (
      <>
        <p>
          The Services are provided on an <strong>“as is”</strong> and{" "}
          <strong>“as available”</strong> basis. To the maximum extent
          permitted by applicable law, we expressly disclaim all warranties of
          any kind, whether express, implied, or statutory, including without
          limitation:
        </p>
        <ul>
          <li>
            warranties of merchantability, fitness for a particular purpose,
            non-infringement, accuracy, completeness, or currency of content;
          </li>
          <li>
            warranties that the Services will be uninterrupted, secure,
            error-free, or free from viruses or other harmful components; and
          </li>
          <li>
            warranties arising from course of dealing or course of
            performance.
          </li>
        </ul>
        <p>
          You acknowledge that you assume sole responsibility for any
          decisions you take based on information obtained through the
          Services and that you should obtain independent professional advice
          before acting on such information.
        </p>
      </>
    ),
  },
  {
    id: "liability",
    number: "12",
    title: "Limitation of Liability",
    body: (
      <>
        <p>
          To the maximum extent permitted by applicable law, in no event shall
          Nyaya Vidhi, its founders, contributors, employees, agents, or
          affiliates be liable for any{" "}
          <strong>
            indirect, incidental, special, consequential, exemplary, or
            punitive damages
          </strong>
          , or for loss of profits, revenue, data, goodwill, or other
          intangible losses, arising out of or in connection with your access
          to or use of, or inability to access or use, the Services.
        </p>
        <p>
          Without limiting the foregoing, our aggregate liability to you for
          all claims arising out of or in connection with the Services,
          whether in contract, tort (including negligence), statute, or
          otherwise, shall not exceed{" "}
          <strong>Indian Rupees One Thousand (INR 1,000)</strong>, that being
          the agreed maximum amount that fairly reflects the gratuitous,
          non-commercial nature of the Services.
        </p>
        <p>
          Some jurisdictions do not permit the exclusion or limitation of
          certain damages; in such jurisdictions, our liability shall be
          limited to the greatest extent permitted by law.
        </p>
      </>
    ),
  },
  {
    id: "indemnity",
    number: "13",
    title: "Indemnity",
    body: (
      <p>
        You agree to defend, indemnify, and hold harmless Nyaya Vidhi and its
        founders, contributors, employees, agents, and affiliates from and
        against any and all claims, demands, suits, proceedings, liabilities,
        damages, losses, costs, and expenses (including reasonable advocates’
        fees) arising out of or in connection with: (a) your access to or use
        of the Services; (b) your breach of these Terms; (c) your violation of
        any applicable law or third-party right; (d) your Submissions or any
        content you upload, transmit, or otherwise make available through the
        Services; or (e) your reliance on any content of the Services without
        obtaining independent professional advice.
      </p>
    ),
  },
  {
    id: "suspension",
    number: "14",
    title: "Suspension & Termination",
    body: (
      <>
        <p>
          We may, at our sole discretion and without prior notice, suspend or
          terminate your access to all or any part of the Services, remove or
          modify any content, and exercise any other remedy available at law,
          if we have reason to believe that you have breached these Terms,
          violated applicable law, or engaged in conduct that may harm us, our
          Users, or any third party.
        </p>
        <p>
          Upon termination, the licence granted under Section 4 shall
          automatically and immediately terminate. Sections 5 (Intellectual
          Property), 7 (Submissions), 11 (Warranties), 12 (Liability), 13
          (Indemnity), 16 (Governing Law), 17 (Dispute Resolution), and any
          other provision which by its nature ought to survive, shall survive
          termination.
        </p>
      </>
    ),
  },
  {
    id: "force-majeure",
    number: "15",
    title: "Force Majeure",
    body: (
      <p>
        We shall not be liable for any failure or delay in the performance of
        the Services to the extent such failure or delay is caused by
        circumstances beyond our reasonable control, including acts of God,
        natural disasters, pandemics or epidemics, war, terrorism, riots,
        civil disturbances, strikes, governmental actions, internet or
        telecommunications failures, or failures of service providers.
      </p>
    ),
  },
  {
    id: "governing-law",
    number: "16",
    title: "Governing Law",
    body: (
      <p>
        These Terms and any non-contractual obligations arising out of or in
        connection with them are governed by and shall be construed in
        accordance with the <strong>laws of the Republic of India</strong>,
        without regard to its conflict-of-laws principles.
      </p>
    ),
  },
  {
    id: "dispute-resolution",
    number: "17",
    title: "Dispute Resolution & Jurisdiction",
    body: (
      <>
        <p>
          The parties shall first attempt to resolve any dispute, controversy,
          difference, or claim arising out of or in connection with these
          Terms (a <strong>“Dispute”</strong>) through good-faith negotiations
          for a period of <strong>thirty (30) days</strong> from the date one
          party notifies the other of the Dispute in writing.
        </p>
        <p>
          If the Dispute is not resolved within the said period, it shall be
          referred to and finally resolved by{" "}
          <strong>arbitration</strong> in accordance with the{" "}
          <strong>Arbitration and Conciliation Act, 1996</strong>, by a sole
          arbitrator to be appointed mutually by the parties or, failing
          agreement, in accordance with the said Act. The seat and venue of
          arbitration shall be <strong>Kolkata, West Bengal</strong>; the
          language of arbitration shall be English; and the award shall be
          final and binding on the parties.
        </p>
        <p>
          Subject to the arbitration clause above, the courts at{" "}
          <strong>Kolkata, West Bengal</strong> shall have{" "}
          <strong>exclusive jurisdiction</strong> over any matter that is not
          arbitrable, including applications under Sections 9, 27, 34, and 36
          of the said Act and any action seeking interim or injunctive
          relief.
        </p>
      </>
    ),
  },
  {
    id: "compliance",
    number: "18",
    title: "Statutory Compliance",
    body: (
      <p>
        These Terms are framed in compliance with applicable laws of India,
        including the Indian Contract Act, 1872; the Specific Relief Act,
        1963; the Information Technology Act, 2000 and the rules made
        thereunder; the Consumer Protection Act, 2019; the Copyright Act,
        1957; the Trade Marks Act, 1999; the Digital Personal Data Protection
        Act, 2023; and the Information Technology (Intermediary Guidelines and
        Digital Media Ethics Code) Rules, 2021.
      </p>
    ),
  },
  {
    id: "changes",
    number: "19",
    title: "Changes to these Terms",
    body: (
      <p>
        We may revise these Terms from time to time. The latest version will
        always be available on this page, with the “Last updated” date
        refreshed accordingly. Where the change is material, we will provide a
        more prominent notice. Your continued use of the Services after the
        revised Terms come into effect constitutes your acceptance of the
        revised Terms.
      </p>
    ),
  },
  {
    id: "general",
    number: "20",
    title: "General Provisions",
    body: (
      <>
        <h4>20.1 Entire Agreement</h4>
        <p>
          These Terms, together with our <a href="/privacy">Privacy Policy</a>{" "}
          and <a href="/disclaimer">Disclaimer</a>, constitute the entire
          agreement between you and us regarding the subject matter hereof and
          supersede any prior or contemporaneous agreements, communications,
          and proposals, whether oral or written.
        </p>
        <h4>20.2 Severability</h4>
        <p>
          If any provision of these Terms is held by a court of competent
          jurisdiction to be invalid, illegal, or unenforceable, that
          provision shall be deemed modified to the minimum extent necessary
          to make it enforceable, and the remaining provisions shall continue
          in full force and effect.
        </p>
        <h4>20.3 No Waiver</h4>
        <p>
          No failure or delay by us in exercising any right, power, or
          privilege under these Terms shall operate as a waiver thereof, nor
          shall any single or partial exercise of any right preclude any
          further or other exercise thereof.
        </p>
        <h4>20.4 Assignment</h4>
        <p>
          You may not assign or transfer these Terms or any rights or
          obligations hereunder, without our prior written consent. We may
          freely assign these Terms in connection with a merger, acquisition,
          restructuring, or sale of assets.
        </p>
        <h4>20.5 Relationship of Parties</h4>
        <p>
          Nothing in these Terms creates a partnership, joint venture,
          agency, employment, franchise, or fiduciary relationship between you
          and us.
        </p>
        <h4>20.6 Notices</h4>
        <p>
          All notices to us shall be in writing and sent to{" "}
          <a href="mailto:legal@nyayavidhi.in">legal@nyayavidhi.in</a>. Notices
          to you may be sent by email to the address you have provided to us
          or by posting a notice on the Platform.
        </p>
      </>
    ),
  },
  {
    id: "contact",
    number: "21",
    title: "Contact",
    body: (
      <div className="rounded-xl border border-ink-100 bg-paper-100/60 p-5">
        <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-ink-400">
          Contact
        </p>
        <p className="mt-2 font-medium text-ink-900">Nyaya Vidhi</p>
        <p className="text-[14px] text-ink-500">
          General queries:{" "}
          <a
            className="text-saffron-700 hover:underline"
            href="mailto:hello@nyayavidhi.in"
          >
            hello@nyayavidhi.in
          </a>
          <br />
          Legal &amp; compliance:{" "}
          <a
            className="text-saffron-700 hover:underline"
            href="mailto:legal@nyayavidhi.in"
          >
            legal@nyayavidhi.in
          </a>
          <br />
          Grievance Officer:{" "}
          <a
            className="text-saffron-700 hover:underline"
            href="mailto:grievance@nyayavidhi.in"
          >
            grievance@nyayavidhi.in
          </a>
          <br />
          Address: Kolkata, West Bengal, India.
        </p>
      </div>
    ),
  },
];

export default function TermsPage() {
  return (
    <LegalPage
      eyebrow="Terms of Use"
      sanskrit="नियमः शास्त्रम् · The rule is the canon"
      title="Terms of Use."
      description="The legally binding agreement between you and Nyaya Vidhi governing your access to and use of the Platform — drafted in accordance with the laws of the Republic of India."
      effectiveDate="01 January 2026"
      lastUpdated="01 January 2026"
      version="1.0"
      preamble={
        <p>
          Please read these Terms carefully before using the Services. They
          set out your rights and obligations and ours, and they limit our
          liability. By accessing or using the Services, you agree to be
          bound by these Terms, our <a href="/privacy">Privacy Policy</a>,
          and our <a href="/disclaimer">Disclaimer</a>. If you do not agree,
          please do not use the Services.
        </p>
      }
      sections={sections}
    />
  );
}
